
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Aug 22 2026 13:47:18 IST (Aug 22 2026 08:17:18 UTC)

// Verification Directory fv/uart_top_design 

module uart_baud_rate(clk, rst, baud_division, en, baud_tick);
  input clk, rst, en;
  input [31:0] baud_division;
  output baud_tick;
  wire clk, rst, en;
  wire [31:0] baud_division;
  wire baud_tick;
  wire [31:0] baud_count;
  wire delayed_en, eq_51_37_n_0, eq_51_37_n_1, eq_51_37_n_2,
       eq_51_37_n_3, eq_51_37_n_4, eq_51_37_n_5, eq_51_37_n_6;
  wire eq_51_37_n_7, eq_51_37_n_8, eq_51_37_n_9, eq_51_37_n_10,
       eq_51_37_n_11, eq_51_37_n_12, eq_51_37_n_13, eq_51_37_n_14;
  wire eq_51_37_n_15, eq_51_37_n_16, eq_51_37_n_17, eq_51_37_n_18,
       eq_51_37_n_19, eq_51_37_n_20, eq_51_37_n_21, eq_51_37_n_22;
  wire eq_51_37_n_23, eq_51_37_n_24, eq_51_37_n_25, eq_51_37_n_26,
       eq_51_37_n_27, eq_51_37_n_28, eq_51_37_n_29, eq_51_37_n_30;
  wire eq_51_37_n_31, eq_51_37_n_32, eq_51_37_n_33, eq_51_37_n_34,
       eq_51_37_n_35, eq_51_37_n_36, eq_51_37_n_37, eq_51_37_n_38;
  wire eq_51_37_n_39, eq_51_37_n_40, eq_51_37_n_41, inc_add_56_46_n_0,
       inc_add_56_46_n_1, inc_add_56_46_n_2, inc_add_56_46_n_3,
       inc_add_56_46_n_4;
  wire inc_add_56_46_n_6, inc_add_56_46_n_8, inc_add_56_46_n_9,
       inc_add_56_46_n_11, inc_add_56_46_n_13, inc_add_56_46_n_15,
       inc_add_56_46_n_17, inc_add_56_46_n_19;
  wire inc_add_56_46_n_21, inc_add_56_46_n_22, inc_add_56_46_n_24,
       inc_add_56_46_n_26, inc_add_56_46_n_28, inc_add_56_46_n_30,
       inc_add_56_46_n_32, inc_add_56_46_n_34;
  wire inc_add_56_46_n_36, inc_add_56_46_n_38, inc_add_56_46_n_40,
       inc_add_56_46_n_42, inc_add_56_46_n_44, inc_add_56_46_n_46,
       inc_add_56_46_n_47, inc_add_56_46_n_49;
  wire inc_add_56_46_n_51, inc_add_56_46_n_53, inc_add_56_46_n_55,
       inc_add_56_46_n_56, inc_add_56_46_n_58, inc_add_56_46_n_60,
       inc_add_56_46_n_62, inc_add_56_46_n_64;
  wire inc_add_56_46_n_66, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire temp_en;
  DFFQXLHVT \baud_count_reg[0] (.CK (clk), .D (n_54), .Q
       (baud_count[0]));
  DFFQXLHVT \baud_count_reg[15] (.CK (clk), .D (n_37), .Q
       (baud_count[15]));
  DFFQXLHVT \baud_count_reg[1] (.CK (clk), .D (n_30), .Q
       (baud_count[1]));
  DFFQXLHVT \baud_count_reg[2] (.CK (clk), .D (n_29), .Q
       (baud_count[2]));
  DFFQXLHVT \baud_count_reg[3] (.CK (clk), .D (n_28), .Q
       (baud_count[3]));
  DFFQXLHVT \baud_count_reg[4] (.CK (clk), .D (n_27), .Q
       (baud_count[4]));
  DFFQXLHVT \baud_count_reg[5] (.CK (clk), .D (n_26), .Q
       (baud_count[5]));
  DFFQXLHVT \baud_count_reg[6] (.CK (clk), .D (n_25), .Q
       (baud_count[6]));
  DFFQXLHVT \baud_count_reg[7] (.CK (clk), .D (n_24), .Q
       (baud_count[7]));
  DFFQXLHVT \baud_count_reg[8] (.CK (clk), .D (n_38), .Q
       (baud_count[8]));
  DFFQXLHVT \baud_count_reg[9] (.CK (clk), .D (n_31), .Q
       (baud_count[9]));
  DFFQXLHVT \baud_count_reg[10] (.CK (clk), .D (n_32), .Q
       (baud_count[10]));
  DFFQXLHVT \baud_count_reg[11] (.CK (clk), .D (n_33), .Q
       (baud_count[11]));
  DFFQXLHVT \baud_count_reg[12] (.CK (clk), .D (n_34), .Q
       (baud_count[12]));
  DFFQXLHVT \baud_count_reg[13] (.CK (clk), .D (n_35), .Q
       (baud_count[13]));
  DFFQXLHVT \baud_count_reg[14] (.CK (clk), .D (n_36), .Q
       (baud_count[14]));
  OAI22XL g1343__2398(.A0 (n_1), .A1 (baud_count[0]), .B0 (n_12), .B1
       (n_19), .Y (n_54));
  DFFQXLHVT \baud_count_reg[31] (.CK (clk), .D (n_46), .Q
       (baud_count[31]));
  DFFQXLHVT \baud_count_reg[17] (.CK (clk), .D (n_39), .Q
       (baud_count[17]));
  DFFQXLHVT \baud_count_reg[18] (.CK (clk), .D (n_40), .Q
       (baud_count[18]));
  DFFQXLHVT \baud_count_reg[19] (.CK (clk), .D (n_41), .Q
       (baud_count[19]));
  DFFQXLHVT \baud_count_reg[20] (.CK (clk), .D (n_42), .Q
       (baud_count[20]));
  DFFQXLHVT \baud_count_reg[21] (.CK (clk), .D (n_43), .Q
       (baud_count[21]));
  DFFQXLHVT \baud_count_reg[22] (.CK (clk), .D (n_44), .Q
       (baud_count[22]));
  DFFQXLHVT \baud_count_reg[23] (.CK (clk), .D (n_45), .Q
       (baud_count[23]));
  DFFQXLHVT \baud_count_reg[24] (.CK (clk), .D (n_53), .Q
       (baud_count[24]));
  DFFQXLHVT \baud_count_reg[25] (.CK (clk), .D (n_47), .Q
       (baud_count[25]));
  DFFQXLHVT \baud_count_reg[26] (.CK (clk), .D (n_48), .Q
       (baud_count[26]));
  DFFQXLHVT \baud_count_reg[27] (.CK (clk), .D (n_49), .Q
       (baud_count[27]));
  DFFQXLHVT \baud_count_reg[28] (.CK (clk), .D (n_50), .Q
       (baud_count[28]));
  DFFQXLHVT \baud_count_reg[29] (.CK (clk), .D (n_51), .Q
       (baud_count[29]));
  DFFQXLHVT \baud_count_reg[30] (.CK (clk), .D (n_52), .Q
       (baud_count[30]));
  DFFQXLHVT \baud_count_reg[16] (.CK (clk), .D (n_23), .Q
       (baud_count[16]));
  NOR2BXLHVT g1360__5107(.AN (n_78), .B (n_22), .Y (n_53));
  NOR2BXLHVT g1361__6260(.AN (n_84), .B (n_22), .Y (n_52));
  NOR2BXLHVT g1362__4319(.AN (n_83), .B (n_22), .Y (n_51));
  NOR2BXLHVT g1363__8428(.AN (n_82), .B (n_22), .Y (n_50));
  NOR2BXLHVT g1364__5526(.AN (n_81), .B (n_22), .Y (n_49));
  NOR2BXLHVT g1365__6783(.AN (n_80), .B (n_1), .Y (n_48));
  NOR2BXLHVT g1366__3680(.AN (n_79), .B (n_22), .Y (n_47));
  NOR2BXLHVT g1367__1617(.AN (n_85), .B (n_22), .Y (n_46));
  NOR2BXLHVT g1368__2802(.AN (n_77), .B (n_22), .Y (n_45));
  NOR2BXLHVT g1369__1705(.AN (n_76), .B (n_22), .Y (n_44));
  NOR2BXLHVT g1370__5122(.AN (n_75), .B (n_1), .Y (n_43));
  NOR2BXLHVT g1371__8246(.AN (n_74), .B (n_22), .Y (n_42));
  NOR2BXLHVT g1372__7098(.AN (n_73), .B (n_1), .Y (n_41));
  NOR2BXLHVT g1373__6131(.AN (n_72), .B (n_22), .Y (n_40));
  NOR2BXLHVT g1374__1881(.AN (n_71), .B (n_1), .Y (n_39));
  NOR2BXLHVT g1375__5115(.AN (n_62), .B (n_1), .Y (n_38));
  NOR2BXLHVT g1376__7482(.AN (n_69), .B (n_1), .Y (n_37));
  NOR2BXLHVT g1377__4733(.AN (n_68), .B (n_22), .Y (n_36));
  NOR2BXLHVT g1378__6161(.AN (n_67), .B (n_22), .Y (n_35));
  NOR2BXLHVT g1379__9315(.AN (n_66), .B (n_1), .Y (n_34));
  NOR2BXLHVT g1380__9945(.AN (n_65), .B (n_22), .Y (n_33));
  NOR2BXLHVT g1381__2883(.AN (n_64), .B (n_1), .Y (n_32));
  NOR2BXLHVT g1382__2346(.AN (n_63), .B (n_1), .Y (n_31));
  NOR2BXLHVT g1383__1666(.AN (n_55), .B (n_1), .Y (n_30));
  NOR2BXLHVT g1384__7410(.AN (n_56), .B (n_1), .Y (n_29));
  NOR2BXLHVT g1385__6417(.AN (n_57), .B (n_22), .Y (n_28));
  NOR2BXLHVT g1386__5477(.AN (n_58), .B (n_1), .Y (n_27));
  NOR2BXLHVT g1387__2398(.AN (n_59), .B (n_22), .Y (n_26));
  NOR2BXLHVT g1388__5107(.AN (n_60), .B (n_1), .Y (n_25));
  NOR2BXLHVT g1389__6260(.AN (n_61), .B (n_1), .Y (n_24));
  NOR2BXLHVT g1390__4319(.AN (n_70), .B (n_1), .Y (n_23));
  NAND2XL g1391__8428(.A (n_12), .B (n_20), .Y (n_22));
  DFFQXLHVT baud_tick_reg(.CK (clk), .D (n_21), .Q (baud_tick));
  NOR2XLHVT g1393__5526(.A (n_14), .B (n_19), .Y (n_21));
  NOR2XLHVT g1394__6783(.A (n_86), .B (n_19), .Y (n_20));
  OR2XLHVT g1395__3680(.A (rst), .B (n_18), .Y (n_19));
  NOR4XLHVT g1396__1617(.A (baud_division[1]), .B (baud_division[3]),
       .C (baud_division[2]), .D (n_17), .Y (n_18));
  NAND4XL g1397__2802(.A (n_3), .B (n_2), .C (n_6), .D (n_16), .Y
       (n_17));
  NOR4XLHVT g1398__1705(.A (baud_division[31]), .B (baud_division[20]),
       .C (baud_division[27]), .D (n_15), .Y (n_16));
  OR4XLHVT g1399__5122(.A (baud_division[30]), .B (baud_division[21]),
       .C (baud_division[22]), .D (n_13), .Y (n_15));
  MXI2XLHVT g1400__8246(.A (baud_tick), .B (n_86), .S0 (n_12), .Y
       (n_14));
  OR4XLHVT g1401__7098(.A (baud_division[19]), .B (baud_division[16]),
       .C (n_7), .D (n_11), .Y (n_13));
  NAND2BXLHVT g1402__6131(.AN (delayed_en), .B (en), .Y (n_12));
  DFFQXLHVT delayed_en_reg(.CK (clk), .D (n_10), .Q (delayed_en));
  NAND3XL g1404__1881(.A (n_4), .B (n_8), .C (n_9), .Y (n_11));
  NOR2BXLHVT g1405__5115(.AN (temp_en), .B (rst), .Y (n_10));
  DFFQXLHVT temp_en_reg(.CK (clk), .D (n_5), .Q (temp_en));
  NOR4XLHVT g1407__7482(.A (baud_division[12]), .B (baud_division[9]),
       .C (baud_division[8]), .D (baud_division[13]), .Y (n_9));
  NOR4XLHVT g1408__4733(.A (baud_division[10]), .B (baud_division[5]),
       .C (baud_division[4]), .D (baud_division[11]), .Y (n_8));
  OR4XLHVT g1409__6161(.A (baud_division[14]), .B (baud_division[17]),
       .C (baud_division[15]), .D (baud_division[18]), .Y (n_7));
  NOR3XLHVT g1410__9315(.A (baud_division[24]), .B (baud_division[23]),
       .C (baud_division[0]), .Y (n_6));
  NOR2BXLHVT g1411__9945(.AN (en), .B (rst), .Y (n_5));
  NOR2XLHVT g1412__2883(.A (baud_division[7]), .B (baud_division[6]),
       .Y (n_4));
  NOR2XLHVT g1413__2346(.A (baud_division[28]), .B (baud_division[25]),
       .Y (n_3));
  NOR2XLHVT g1414__1666(.A (baud_division[29]), .B (baud_division[26]),
       .Y (n_2));
  INVXLHVT drc_bufs1420(.A (n_0), .Y (n_1));
  INVXLHVT drc_bufs1421(.A (n_22), .Y (n_0));
  NOR4XLHVT eq_51_37_g797__7410(.A (eq_51_37_n_32), .B (eq_51_37_n_36),
       .C (eq_51_37_n_38), .D (eq_51_37_n_41), .Y (n_86));
  NAND4XL eq_51_37_g798__6417(.A (eq_51_37_n_10), .B (eq_51_37_n_14),
       .C (eq_51_37_n_34), .D (eq_51_37_n_40), .Y (eq_51_37_n_41));
  NOR4XLHVT eq_51_37_g799__5477(.A (eq_51_37_n_33), .B (eq_51_37_n_35),
       .C (eq_51_37_n_39), .D (eq_51_37_n_37), .Y (eq_51_37_n_40));
  NAND4XL eq_51_37_g800__2398(.A (eq_51_37_n_18), .B (eq_51_37_n_22),
       .C (eq_51_37_n_21), .D (eq_51_37_n_28), .Y (eq_51_37_n_39));
  NAND4XL eq_51_37_g801__5107(.A (eq_51_37_n_17), .B (eq_51_37_n_24),
       .C (eq_51_37_n_20), .D (eq_51_37_n_1), .Y (eq_51_37_n_38));
  NAND4XL eq_51_37_g802__6260(.A (eq_51_37_n_9), .B (eq_51_37_n_31), .C
       (eq_51_37_n_12), .D (eq_51_37_n_11), .Y (eq_51_37_n_37));
  NAND4XL eq_51_37_g803__4319(.A (eq_51_37_n_13), .B (eq_51_37_n_4), .C
       (eq_51_37_n_16), .D (eq_51_37_n_19), .Y (eq_51_37_n_36));
  NAND4XL eq_51_37_g804__8428(.A (eq_51_37_n_2), .B (eq_51_37_n_8), .C
       (eq_51_37_n_6), .D (eq_51_37_n_5), .Y (eq_51_37_n_35));
  AND4XL eq_51_37_g805__5526(.A (eq_51_37_n_0), .B (eq_51_37_n_23), .C
       (eq_51_37_n_26), .D (eq_51_37_n_29), .Y (eq_51_37_n_34));
  NAND4XL eq_51_37_g806__6783(.A (eq_51_37_n_25), .B (eq_51_37_n_15),
       .C (eq_51_37_n_30), .D (eq_51_37_n_27), .Y (eq_51_37_n_33));
  NAND2XL eq_51_37_g807__3680(.A (eq_51_37_n_3), .B (eq_51_37_n_7), .Y
       (eq_51_37_n_32));
  XNOR2XLHVT eq_51_37_g808__1617(.A (baud_division[11]), .B
       (baud_count[11]), .Y (eq_51_37_n_31));
  XNOR2XLHVT eq_51_37_g809__2802(.A (baud_division[1]), .B
       (baud_count[1]), .Y (eq_51_37_n_30));
  XNOR2XLHVT eq_51_37_g810__1705(.A (baud_division[27]), .B
       (baud_count[27]), .Y (eq_51_37_n_29));
  XNOR2XLHVT eq_51_37_g811__5122(.A (baud_division[13]), .B
       (baud_count[13]), .Y (eq_51_37_n_28));
  XNOR2XLHVT eq_51_37_g812__8246(.A (baud_division[5]), .B
       (baud_count[5]), .Y (eq_51_37_n_27));
  XNOR2XLHVT eq_51_37_g813__7098(.A (baud_division[26]), .B
       (baud_count[26]), .Y (eq_51_37_n_26));
  XNOR2XLHVT eq_51_37_g814__6131(.A (baud_division[0]), .B
       (baud_count[0]), .Y (eq_51_37_n_25));
  XNOR2XLHVT eq_51_37_g815__1881(.A (baud_division[21]), .B
       (baud_count[21]), .Y (eq_51_37_n_24));
  XNOR2XLHVT eq_51_37_g816__5115(.A (baud_division[25]), .B
       (baud_count[25]), .Y (eq_51_37_n_23));
  XNOR2XLHVT eq_51_37_g817__7482(.A (baud_division[15]), .B
       (baud_count[15]), .Y (eq_51_37_n_22));
  XNOR2XLHVT eq_51_37_g818__4733(.A (baud_division[14]), .B
       (baud_count[14]), .Y (eq_51_37_n_21));
  XNOR2XLHVT eq_51_37_g819__6161(.A (baud_division[18]), .B
       (baud_count[18]), .Y (eq_51_37_n_20));
  XNOR2XLHVT eq_51_37_g820__9315(.A (baud_division[30]), .B
       (baud_count[30]), .Y (eq_51_37_n_19));
  XNOR2XLHVT eq_51_37_g821__9945(.A (baud_division[12]), .B
       (baud_count[12]), .Y (eq_51_37_n_18));
  XNOR2XLHVT eq_51_37_g822__2883(.A (baud_division[17]), .B
       (baud_count[17]), .Y (eq_51_37_n_17));
  XNOR2XLHVT eq_51_37_g823__2346(.A (baud_division[22]), .B
       (baud_count[22]), .Y (eq_51_37_n_16));
  XNOR2XLHVT eq_51_37_g824__1666(.A (baud_division[6]), .B
       (baud_count[6]), .Y (eq_51_37_n_15));
  XNOR2XLHVT eq_51_37_g825__7410(.A (baud_division[29]), .B
       (baud_count[29]), .Y (eq_51_37_n_14));
  XNOR2XLHVT eq_51_37_g826__6417(.A (baud_division[19]), .B
       (baud_count[19]), .Y (eq_51_37_n_13));
  XNOR2XLHVT eq_51_37_g827__5477(.A (baud_division[10]), .B
       (baud_count[10]), .Y (eq_51_37_n_12));
  XNOR2XLHVT eq_51_37_g828__2398(.A (baud_division[9]), .B
       (baud_count[9]), .Y (eq_51_37_n_11));
  XNOR2XLHVT eq_51_37_g829__5107(.A (baud_division[28]), .B
       (baud_count[28]), .Y (eq_51_37_n_10));
  XNOR2XLHVT eq_51_37_g830__6260(.A (baud_division[8]), .B
       (baud_count[8]), .Y (eq_51_37_n_9));
  XNOR2XLHVT eq_51_37_g831__4319(.A (baud_division[4]), .B
       (baud_count[4]), .Y (eq_51_37_n_8));
  XNOR2XLHVT eq_51_37_g832__8428(.A (baud_division[31]), .B
       (baud_count[31]), .Y (eq_51_37_n_7));
  XNOR2XLHVT eq_51_37_g833__5526(.A (baud_division[3]), .B
       (baud_count[3]), .Y (eq_51_37_n_6));
  XNOR2XLHVT eq_51_37_g834__6783(.A (baud_division[7]), .B
       (baud_count[7]), .Y (eq_51_37_n_5));
  XNOR2XLHVT eq_51_37_g835__3680(.A (baud_division[23]), .B
       (baud_count[23]), .Y (eq_51_37_n_4));
  XNOR2XLHVT eq_51_37_g836__1617(.A (baud_division[16]), .B
       (baud_count[16]), .Y (eq_51_37_n_3));
  XNOR2XLHVT eq_51_37_g837__2802(.A (baud_division[2]), .B
       (baud_count[2]), .Y (eq_51_37_n_2));
  XNOR2XLHVT eq_51_37_g838__1705(.A (baud_division[20]), .B
       (baud_count[20]), .Y (eq_51_37_n_1));
  XNOR2XLHVT eq_51_37_g839__5122(.A (baud_division[24]), .B
       (baud_count[24]), .Y (eq_51_37_n_0));
  XNOR2XLHVT inc_add_56_46_g407__8246(.A (baud_count[31]), .B
       (inc_add_56_46_n_66), .Y (n_85));
  OA21XLHVT inc_add_56_46_g408__7098(.A0 (baud_count[30]), .A1
       (inc_add_56_46_n_64), .B0 (inc_add_56_46_n_66), .Y (n_84));
  NAND2XL inc_add_56_46_g409__6131(.A (baud_count[30]), .B
       (inc_add_56_46_n_64), .Y (inc_add_56_46_n_66));
  XNOR2XLHVT inc_add_56_46_g410__1881(.A (baud_count[29]), .B
       (inc_add_56_46_n_62), .Y (n_83));
  NOR2BXLHVT inc_add_56_46_g411__5115(.AN (baud_count[29]), .B
       (inc_add_56_46_n_62), .Y (inc_add_56_46_n_64));
  OA21XLHVT inc_add_56_46_g412__7482(.A0 (baud_count[28]), .A1
       (inc_add_56_46_n_60), .B0 (inc_add_56_46_n_62), .Y (n_82));
  NAND2XL inc_add_56_46_g413__4733(.A (baud_count[28]), .B
       (inc_add_56_46_n_60), .Y (inc_add_56_46_n_62));
  XNOR2XLHVT inc_add_56_46_g414__6161(.A (baud_count[27]), .B
       (inc_add_56_46_n_58), .Y (n_81));
  NOR2BXLHVT inc_add_56_46_g415__9315(.AN (baud_count[27]), .B
       (inc_add_56_46_n_58), .Y (inc_add_56_46_n_60));
  OA21XLHVT inc_add_56_46_g416__9945(.A0 (baud_count[26]), .A1
       (inc_add_56_46_n_56), .B0 (inc_add_56_46_n_58), .Y (n_80));
  NAND2XL inc_add_56_46_g417__2883(.A (baud_count[26]), .B
       (inc_add_56_46_n_56), .Y (inc_add_56_46_n_58));
  NOR2XLHVT inc_add_56_46_g418__2346(.A (inc_add_56_46_n_55), .B
       (inc_add_56_46_n_56), .Y (n_79));
  NOR2BXLHVT inc_add_56_46_g419__1666(.AN (baud_count[25]), .B
       (inc_add_56_46_n_53), .Y (inc_add_56_46_n_56));
  NOR2BXLHVT inc_add_56_46_g420__7410(.AN (inc_add_56_46_n_53), .B
       (baud_count[25]), .Y (inc_add_56_46_n_55));
  OA21XLHVT inc_add_56_46_g421__6417(.A0 (baud_count[24]), .A1
       (inc_add_56_46_n_51), .B0 (inc_add_56_46_n_53), .Y (n_78));
  NAND2XL inc_add_56_46_g422__5477(.A (baud_count[24]), .B
       (inc_add_56_46_n_51), .Y (inc_add_56_46_n_53));
  XNOR2XLHVT inc_add_56_46_g423__2398(.A (baud_count[23]), .B
       (inc_add_56_46_n_49), .Y (n_77));
  NOR2BXLHVT inc_add_56_46_g424__5107(.AN (baud_count[23]), .B
       (inc_add_56_46_n_49), .Y (inc_add_56_46_n_51));
  OA21XLHVT inc_add_56_46_g425__6260(.A0 (baud_count[22]), .A1
       (inc_add_56_46_n_47), .B0 (inc_add_56_46_n_49), .Y (n_76));
  NAND2XL inc_add_56_46_g426__4319(.A (baud_count[22]), .B
       (inc_add_56_46_n_47), .Y (inc_add_56_46_n_49));
  NOR2XLHVT inc_add_56_46_g427__8428(.A (inc_add_56_46_n_46), .B
       (inc_add_56_46_n_47), .Y (n_75));
  NOR2BXLHVT inc_add_56_46_g428__5526(.AN (baud_count[21]), .B
       (inc_add_56_46_n_44), .Y (inc_add_56_46_n_47));
  NOR2BXLHVT inc_add_56_46_g429__6783(.AN (inc_add_56_46_n_44), .B
       (baud_count[21]), .Y (inc_add_56_46_n_46));
  XNOR2XLHVT inc_add_56_46_g430__3680(.A (baud_count[20]), .B
       (inc_add_56_46_n_42), .Y (n_74));
  NAND2BXLHVT inc_add_56_46_g431__1617(.AN (inc_add_56_46_n_42), .B
       (baud_count[20]), .Y (inc_add_56_46_n_44));
  OA21XLHVT inc_add_56_46_g432__2802(.A0 (baud_count[19]), .A1
       (inc_add_56_46_n_40), .B0 (inc_add_56_46_n_42), .Y (n_73));
  NAND2XL inc_add_56_46_g433__1705(.A (baud_count[19]), .B
       (inc_add_56_46_n_40), .Y (inc_add_56_46_n_42));
  AOI21XL inc_add_56_46_g434__5122(.A0 (inc_add_56_46_n_1), .A1
       (inc_add_56_46_n_38), .B0 (inc_add_56_46_n_40), .Y (n_72));
  NOR2XLHVT inc_add_56_46_g435__8246(.A (inc_add_56_46_n_1), .B
       (inc_add_56_46_n_38), .Y (inc_add_56_46_n_40));
  XNOR2XLHVT inc_add_56_46_g436__7098(.A (baud_count[17]), .B
       (inc_add_56_46_n_36), .Y (n_71));
  NAND2BXLHVT inc_add_56_46_g437__6131(.AN (inc_add_56_46_n_36), .B
       (baud_count[17]), .Y (inc_add_56_46_n_38));
  XNOR2XLHVT inc_add_56_46_g438__1881(.A (baud_count[16]), .B
       (inc_add_56_46_n_34), .Y (n_70));
  NAND2BXLHVT inc_add_56_46_g439__5115(.AN (inc_add_56_46_n_34), .B
       (baud_count[16]), .Y (inc_add_56_46_n_36));
  OA21XLHVT inc_add_56_46_g440__7482(.A0 (baud_count[15]), .A1
       (inc_add_56_46_n_32), .B0 (inc_add_56_46_n_34), .Y (n_69));
  NAND2XL inc_add_56_46_g441__4733(.A (baud_count[15]), .B
       (inc_add_56_46_n_32), .Y (inc_add_56_46_n_34));
  AOI21XL inc_add_56_46_g442__6161(.A0 (inc_add_56_46_n_0), .A1
       (inc_add_56_46_n_30), .B0 (inc_add_56_46_n_32), .Y (n_68));
  NOR2XLHVT inc_add_56_46_g443__9315(.A (inc_add_56_46_n_0), .B
       (inc_add_56_46_n_30), .Y (inc_add_56_46_n_32));
  XNOR2XLHVT inc_add_56_46_g444__9945(.A (baud_count[13]), .B
       (inc_add_56_46_n_28), .Y (n_67));
  NAND2BXLHVT inc_add_56_46_g445__2883(.AN (inc_add_56_46_n_28), .B
       (baud_count[13]), .Y (inc_add_56_46_n_30));
  OA21XLHVT inc_add_56_46_g446__2346(.A0 (baud_count[12]), .A1
       (inc_add_56_46_n_26), .B0 (inc_add_56_46_n_28), .Y (n_66));
  NAND2XL inc_add_56_46_g447__1666(.A (baud_count[12]), .B
       (inc_add_56_46_n_26), .Y (inc_add_56_46_n_28));
  XNOR2XLHVT inc_add_56_46_g448__7410(.A (baud_count[11]), .B
       (inc_add_56_46_n_24), .Y (n_65));
  NOR2BXLHVT inc_add_56_46_g449__6417(.AN (baud_count[11]), .B
       (inc_add_56_46_n_24), .Y (inc_add_56_46_n_26));
  OA21XLHVT inc_add_56_46_g450__5477(.A0 (baud_count[10]), .A1
       (inc_add_56_46_n_22), .B0 (inc_add_56_46_n_24), .Y (n_64));
  NAND2XL inc_add_56_46_g451__2398(.A (baud_count[10]), .B
       (inc_add_56_46_n_22), .Y (inc_add_56_46_n_24));
  NOR2XLHVT inc_add_56_46_g452__5107(.A (inc_add_56_46_n_21), .B
       (inc_add_56_46_n_22), .Y (n_63));
  NOR2BXLHVT inc_add_56_46_g453__6260(.AN (baud_count[9]), .B
       (inc_add_56_46_n_19), .Y (inc_add_56_46_n_22));
  NOR2BXLHVT inc_add_56_46_g454__4319(.AN (inc_add_56_46_n_19), .B
       (baud_count[9]), .Y (inc_add_56_46_n_21));
  XNOR2XLHVT inc_add_56_46_g455__8428(.A (baud_count[8]), .B
       (inc_add_56_46_n_17), .Y (n_62));
  NAND2BXLHVT inc_add_56_46_g456__5526(.AN (inc_add_56_46_n_17), .B
       (baud_count[8]), .Y (inc_add_56_46_n_19));
  OA21XLHVT inc_add_56_46_g457__6783(.A0 (baud_count[7]), .A1
       (inc_add_56_46_n_15), .B0 (inc_add_56_46_n_17), .Y (n_61));
  NAND2XL inc_add_56_46_g458__3680(.A (baud_count[7]), .B
       (inc_add_56_46_n_15), .Y (inc_add_56_46_n_17));
  AOI21XL inc_add_56_46_g459__1617(.A0 (inc_add_56_46_n_2), .A1
       (inc_add_56_46_n_13), .B0 (inc_add_56_46_n_15), .Y (n_60));
  NOR2XLHVT inc_add_56_46_g460__2802(.A (inc_add_56_46_n_2), .B
       (inc_add_56_46_n_13), .Y (inc_add_56_46_n_15));
  XNOR2XLHVT inc_add_56_46_g461__1705(.A (baud_count[5]), .B
       (inc_add_56_46_n_11), .Y (n_59));
  NAND2BXLHVT inc_add_56_46_g462__5122(.AN (inc_add_56_46_n_11), .B
       (baud_count[5]), .Y (inc_add_56_46_n_13));
  OA21XLHVT inc_add_56_46_g463__8246(.A0 (baud_count[4]), .A1
       (inc_add_56_46_n_9), .B0 (inc_add_56_46_n_11), .Y (n_58));
  NAND2XL inc_add_56_46_g464__7098(.A (baud_count[4]), .B
       (inc_add_56_46_n_9), .Y (inc_add_56_46_n_11));
  NOR2XLHVT inc_add_56_46_g465__6131(.A (inc_add_56_46_n_8), .B
       (inc_add_56_46_n_9), .Y (n_57));
  NOR2BXLHVT inc_add_56_46_g466__1881(.AN (baud_count[3]), .B
       (inc_add_56_46_n_6), .Y (inc_add_56_46_n_9));
  NOR2BXLHVT inc_add_56_46_g467__5115(.AN (inc_add_56_46_n_6), .B
       (baud_count[3]), .Y (inc_add_56_46_n_8));
  OA21XLHVT inc_add_56_46_g468__7482(.A0 (baud_count[2]), .A1
       (inc_add_56_46_n_3), .B0 (inc_add_56_46_n_6), .Y (n_56));
  NAND2XL inc_add_56_46_g469__4733(.A (baud_count[2]), .B
       (inc_add_56_46_n_3), .Y (inc_add_56_46_n_6));
  NOR2XLHVT inc_add_56_46_g470__6161(.A (inc_add_56_46_n_4), .B
       (inc_add_56_46_n_3), .Y (n_55));
  NOR2XLHVT inc_add_56_46_g471__9315(.A (baud_count[1]), .B
       (baud_count[0]), .Y (inc_add_56_46_n_4));
  AND2XLHVT inc_add_56_46_g472__9945(.A (baud_count[0]), .B
       (baud_count[1]), .Y (inc_add_56_46_n_3));
  INVXLHVT inc_add_56_46_g473(.A (baud_count[6]), .Y
       (inc_add_56_46_n_2));
  INVXLHVT inc_add_56_46_g474(.A (baud_count[18]), .Y
       (inc_add_56_46_n_1));
  INVXLHVT inc_add_56_46_g475(.A (baud_count[14]), .Y
       (inc_add_56_46_n_0));
endmodule

module uart_rx(clk, rst, baud_tick, rx, ext_data_out);
  input clk, rst, baud_tick, rx;
  output [7:0] ext_data_out;
  wire clk, rst, baud_tick, rx;
  wire [7:0] ext_data_out;
  wire [1:0] next_state;
  wire [1:0] current_state;
  wire [7:0] data_save;
  wire [2:0] count_8;
  wire [3:0] count_16;
  wire UNCONNECTED, UNCONNECTED0, count_8_indication,
       count_16_indication, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64;
  INVXLHVT g1338(.A (count_8_indication), .Y (n_60));
  INVXLHVT g1339(.A (count_16_indication), .Y (n_59));
  TLATNXLHVT \next_state_reg[0] (.GN (n_58), .D (n_51), .Q
       (next_state[0]), .QN (UNCONNECTED));
  TLATNXLHVT \next_state_reg[1] (.GN (n_58), .D (n_55), .Q
       (next_state[1]), .QN (UNCONNECTED0));
  NOR2XLHVT g1439__2883(.A (rst), .B (n_57), .Y (n_58));
  OAI222XL g1440__2346(.A0 (n_59), .A1 (n_56), .B0 (n_60), .B1 (n_64),
       .C0 (current_state[0]), .C1 (n_54), .Y (n_57));
  AOI31XL g1441__1666(.A0 (current_state[1]), .A1 (current_state[0]),
       .A2 (rx), .B0 (n_53), .Y (n_56));
  NAND2XL g1442__7410(.A (n_63), .B (n_61), .Y (n_55));
  DFFQXLHVT \ext_data_out_reg[6] (.CK (clk), .D (n_47), .Q
       (ext_data_out[6]));
  DFFQXLHVT \ext_data_out_reg[4] (.CK (clk), .D (n_46), .Q
       (ext_data_out[4]));
  DFFQXLHVT \ext_data_out_reg[0] (.CK (clk), .D (n_44), .Q
       (ext_data_out[0]));
  OR2XLHVT g1446__6417(.A (rst), .B (n_64), .Y (n_63));
  OR2XLHVT g1447__5477(.A (current_state[1]), .B (n_62), .Y (n_61));
  DFFQXLHVT \ext_data_out_reg[5] (.CK (clk), .D (n_48), .Q
       (ext_data_out[5]));
  DFFQXLHVT \ext_data_out_reg[2] (.CK (clk), .D (n_52), .Q
       (ext_data_out[2]));
  DFFQXLHVT \ext_data_out_reg[3] (.CK (clk), .D (n_49), .Q
       (ext_data_out[3]));
  DFFQXLHVT \ext_data_out_reg[7] (.CK (clk), .D (n_45), .Q
       (ext_data_out[7]));
  DFFQXLHVT \ext_data_out_reg[1] (.CK (clk), .D (n_50), .Q
       (ext_data_out[1]));
  INVXLHVT g1453(.A (n_53), .Y (n_54));
  NOR2BXLHVT g1454__2398(.AN (data_save[2]), .B (rst), .Y (n_52));
  NOR2XLHVT g1455__5107(.A (rst), .B (current_state[0]), .Y (n_51));
  NOR2BXLHVT g1456__6260(.AN (data_save[1]), .B (rst), .Y (n_50));
  NAND2XL g1457__4319(.A (n_0), .B (current_state[0]), .Y (n_62));
  NOR2XLHVT g1458__8428(.A (current_state[1]), .B (rx), .Y (n_53));
  NAND2XL g1459__5526(.A (current_state[1]), .B (n_43), .Y (n_64));
  AND2XLHVT g1460__6783(.A (n_0), .B (data_save[3]), .Y (n_49));
  AND2XLHVT g1461__3680(.A (n_0), .B (data_save[5]), .Y (n_48));
  AND2XLHVT g1462__1617(.A (n_0), .B (data_save[6]), .Y (n_47));
  AND2XLHVT g1463__2802(.A (n_0), .B (data_save[4]), .Y (n_46));
  AND2XLHVT g1464__1705(.A (n_0), .B (data_save[7]), .Y (n_45));
  AND2XLHVT g1465__5122(.A (n_0), .B (data_save[0]), .Y (n_44));
  INVXLHVT g1466(.A (current_state[0]), .Y (n_43));
  INVXLHVT g1467(.A (rst), .Y (n_0));
  DFFQXLHVT \count_8_reg[2] (.CK (clk), .D (n_41), .Q (count_8[2]));
  OAI31XL g1877__8246(.A0 (count_8[2]), .A1 (n_3), .A2 (n_26), .B0
       (n_30), .Y (n_41));
  DFFQXLHVT \data_save_reg[7] (.CK (clk), .D (n_38), .Q (data_save[7]));
  DFFQXLHVT \data_save_reg[6] (.CK (clk), .D (n_32), .Q (data_save[6]));
  DFFQXLHVT \data_save_reg[0] (.CK (clk), .D (n_40), .Q (data_save[0]));
  DFFQXLHVT \count_16_reg[3] (.CK (clk), .D (n_31), .Q (count_16[3]));
  SDFFQXLHVT \count_8_reg[1] (.CK (clk), .D (n_27), .SI (n_25), .SE
       (count_8[1]), .Q (count_8[1]));
  DFFQXLHVT count_8_indication_reg(.CK (clk), .D (n_39), .Q
       (count_8_indication));
  DFFQXLHVT \data_save_reg[1] (.CK (clk), .D (n_37), .Q (data_save[1]));
  DFFQXLHVT \data_save_reg[2] (.CK (clk), .D (n_36), .Q (data_save[2]));
  DFFQXLHVT \data_save_reg[3] (.CK (clk), .D (n_35), .Q (data_save[3]));
  DFFQXLHVT \data_save_reg[4] (.CK (clk), .D (n_34), .Q (data_save[4]));
  DFFQXLHVT \data_save_reg[5] (.CK (clk), .D (n_33), .Q (data_save[5]));
  AO22XLHVT g1889__7098(.A0 (data_save[0]), .A1 (n_23), .B0 (n_20), .B1
       (rx), .Y (n_40));
  NOR3BXLHVT g1890__6131(.AN (count_8[2]), .B (n_3), .C (n_26), .Y
       (n_39));
  AO22XLHVT g1891__1881(.A0 (data_save[7]), .A1 (n_23), .B0
       (data_save[6]), .B1 (n_20), .Y (n_38));
  AO22XLHVT g1892__5115(.A0 (data_save[1]), .A1 (n_23), .B0
       (data_save[0]), .B1 (n_20), .Y (n_37));
  AO22XLHVT g1893__7482(.A0 (data_save[2]), .A1 (n_23), .B0
       (data_save[1]), .B1 (n_20), .Y (n_36));
  AO22XLHVT g1894__4733(.A0 (data_save[3]), .A1 (n_23), .B0
       (data_save[2]), .B1 (n_20), .Y (n_35));
  AO22XLHVT g1895__6161(.A0 (data_save[4]), .A1 (n_23), .B0
       (data_save[3]), .B1 (n_20), .Y (n_34));
  AO22XLHVT g1896__9315(.A0 (data_save[5]), .A1 (n_23), .B0
       (data_save[4]), .B1 (n_20), .Y (n_33));
  AO22XLHVT g1897__9945(.A0 (data_save[6]), .A1 (n_23), .B0
       (data_save[5]), .B1 (n_20), .Y (n_32));
  OAI31XL g1898__2883(.A0 (count_16[3]), .A1 (n_7), .A2 (n_11), .B0
       (n_29), .Y (n_31));
  DFFQXLHVT \count_16_reg[2] (.CK (clk), .D (n_28), .Q (count_16[2]));
  SDFFQXLHVT \count_8_reg[0] (.CK (clk), .D (n_20), .SI (n_17), .SE
       (count_8[0]), .Q (count_8[0]));
  OAI21XL g1901__2346(.A0 (n_9), .A1 (n_17), .B0 (count_8[2]), .Y
       (n_30));
  NAND2XL g1902__1666(.A (count_16[3]), .B (n_24), .Y (n_29));
  OAI32XLHVT g1903__7410(.A0 (count_16[2]), .A1 (n_8), .A2 (n_10), .B0
       (n_4), .B1 (n_18), .Y (n_28));
  DFFQXLHVT count_16_indication_reg(.CK (clk), .D (n_22), .Q
       (count_16_indication));
  DFFQXLHVT \count_16_reg[1] (.CK (clk), .D (n_21), .Q (count_16[1]));
  INVXLHVT g1906(.A (n_26), .Y (n_27));
  OAI21XL g1907__6417(.A0 (count_8[0]), .A1 (n_63), .B0 (n_16), .Y
       (n_25));
  OAI21XL g1908__5477(.A0 (count_16[2]), .A1 (n_10), .B0 (n_18), .Y
       (n_24));
  NAND2XL g1909__2398(.A (count_8[0]), .B (n_20), .Y (n_26));
  OAI32XLHVT g1910__5107(.A0 (count_16[3]), .A1 (n_61), .A2 (n_11), .B0
       (n_7), .B1 (n_15), .Y (n_22));
  OAI2BB1XLHVT g1911__6260(.A0N (count_16[1]), .A1N (n_14), .B0 (n_12),
       .Y (n_21));
  NOR2XLHVT g1912__4319(.A (rst), .B (n_19), .Y (n_23));
  NOR2XLHVT g1913__8428(.A (n_64), .B (n_15), .Y (n_19));
  NOR2XLHVT g1914__5526(.A (n_63), .B (n_15), .Y (n_20));
  INVXLHVT g1915(.A (n_16), .Y (n_17));
  AOI2BB1XLHVT g1916__6783(.A0N (count_16[1]), .A1N (n_10), .B0 (n_14),
       .Y (n_18));
  NAND2BXLHVT g1917__3680(.AN (n_63), .B (n_15), .Y (n_16));
  DFFQXLHVT \count_16_reg[0] (.CK (clk), .D (n_13), .Q (count_16[0]));
  NAND2BXLHVT g1919__1617(.AN (n_11), .B (count_16[3]), .Y (n_15));
  OAI33XLHVT g1920__2802(.A0 (count_16[0]), .A1 (n_1), .A2 (n_10), .B0
       (baud_tick), .B1 (rst), .B2 (n_2), .Y (n_13));
  OAI22XL g1921__1705(.A0 (count_16[0]), .A1 (n_10), .B0 (rst), .B1
       (baud_tick), .Y (n_14));
  OR4XLHVT g1922__5122(.A (count_16[1]), .B (n_2), .C (n_1), .D (n_10),
       .Y (n_12));
  OR2XLHVT g1923__8246(.A (n_4), .B (n_8), .Y (n_11));
  AOI21XL g1924__7098(.A0 (count_8[0]), .A1 (count_8[1]), .B0 (n_63),
       .Y (n_9));
  AND2XLHVT g1925__6131(.A (n_7), .B (n_62), .Y (n_10));
  DFFQXLHVT \current_state_reg[0] (.CK (clk), .D (n_6), .Q
       (current_state[0]));
  NAND3XL g1927__1881(.A (count_16[0]), .B (count_16[1]), .C
       (baud_tick), .Y (n_8));
  DFFQXLHVT \current_state_reg[1] (.CK (clk), .D (n_5), .Q
       (current_state[1]));
  NAND2XL g1929__5115(.A (n_0), .B (current_state[1]), .Y (n_7));
  AND2XLHVT g1930__7482(.A (n_0), .B (next_state[0]), .Y (n_6));
  AND2XLHVT g1931__4733(.A (n_0), .B (next_state[1]), .Y (n_5));
  INVXLHVT g1932(.A (count_16[2]), .Y (n_4));
  INVXLHVT g1933(.A (count_8[1]), .Y (n_3));
  INVXLHVT g1934(.A (count_16[0]), .Y (n_2));
  INVXLHVT g1935(.A (baud_tick), .Y (n_1));
endmodule

module uart_tx(clk, rst, baud_tick, ext_data_in, en, tx);
  input clk, rst, baud_tick, en;
  input [7:0] ext_data_in;
  output tx;
  wire clk, rst, baud_tick, en;
  wire [7:0] ext_data_in;
  wire tx;
  wire [1:0] next_state;
  wire [1:0] current_state;
  wire [3:0] count_16;
  wire [7:0] data_save;
  wire [2:0] count_8;
  wire UNCONNECTED1, UNCONNECTED2, UNCONNECTED3, count_8_indication,
       count_16_indication, n_0, n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  TLATXLHVT \next_state_reg[0] (.G (n_60), .D (n_50), .Q
       (next_state[0]), .QN (UNCONNECTED1));
  TLATXLHVT \next_state_reg[1] (.G (n_60), .D (n_57), .Q
       (next_state[1]), .QN (UNCONNECTED2));
  NAND2XL g1349__6161(.A (n_48), .B (n_59), .Y (n_60));
  AOI222XL g1350__9315(.A0 (count_16_indication), .A1
       (current_state[0]), .B0 (en), .B1 (n_53), .C0
       (count_8_indication), .C1 (n_56), .Y (n_59));
  DFFQXLHVT count_16_indication_reg(.CK (clk), .D (n_58), .Q
       (count_16_indication));
  NOR2XLHVT g1352__9945(.A (n_63), .B (n_64), .Y (n_58));
  AOI21XL g1353__2883(.A0 (n_52), .A1 (n_61), .B0 (rst), .Y (n_57));
  NAND2XL g1354__2346(.A (n_48), .B (n_56), .Y (n_65));
  TLATNX2 tx_reg(.GN (rst), .D (n_55), .Q (tx), .QN (UNCONNECTED3));
  INVXLHVT g1356(.A (n_61), .Y (n_56));
  NAND4XL g1357__1666(.A (count_16[2]), .B (count_16[3]), .C
       (baud_tick), .D (n_51), .Y (n_64));
  NAND2BXLHVT g1358__7410(.AN (n_53), .B (n_54), .Y (n_55));
  OR2XLHVT g1359__6417(.A (rst), .B (n_53), .Y (n_63));
  OAI21XL g1360__5477(.A0 (data_save[7]), .A1 (current_state[0]), .B0
       (current_state[1]), .Y (n_54));
  NAND2BXLHVT g1361__2398(.AN (current_state[1]), .B
       (current_state[0]), .Y (n_52));
  NOR2XLHVT g1362__5107(.A (current_state[0]), .B (current_state[1]),
       .Y (n_53));
  INVXLHVT g1363(.A (n_62), .Y (n_51));
  NOR2XLHVT g1364__6260(.A (rst), .B (current_state[0]), .Y (n_50));
  NAND2XL g1365__4319(.A (count_16[0]), .B (count_16[1]), .Y (n_62));
  NAND2XL g1366__8428(.A (current_state[1]), .B (n_49), .Y (n_61));
  INVXLHVT g1367(.A (current_state[0]), .Y (n_49));
  INVXLHVT g1368(.A (rst), .Y (n_48));
  DFFQXLHVT \count_8_reg[2] (.CK (clk), .D (n_47), .Q (count_8[2]));
  DFFQXLHVT \data_save_reg[6] (.CK (clk), .D (n_45), .Q (data_save[6]));
  DFFQXLHVT \data_save_reg[3] (.CK (clk), .D (n_46), .Q (data_save[3]));
  NOR2XLHVT g1718__5526(.A (n_65), .B (n_34), .Y (n_47));
  OAI2BB1XLHVT g1719__6783(.A0N (data_save[2]), .A1N (n_20), .B0
       (n_31), .Y (n_46));
  OAI2BB1XLHVT g1720__3680(.A0N (data_save[5]), .A1N (n_20), .B0
       (n_33), .Y (n_45));
  DFFQXLHVT \data_save_reg[0] (.CK (clk), .D (n_32), .Q (data_save[0]));
  DFFQXLHVT \data_save_reg[1] (.CK (clk), .D (n_43), .Q (data_save[1]));
  DFFQXLHVT \data_save_reg[7] (.CK (clk), .D (n_42), .Q (data_save[7]));
  DFFQXLHVT \data_save_reg[5] (.CK (clk), .D (n_40), .Q (data_save[5]));
  DFFQXLHVT \data_save_reg[2] (.CK (clk), .D (n_44), .Q (data_save[2]));
  DFFQXLHVT \data_save_reg[4] (.CK (clk), .D (n_41), .Q (data_save[4]));
  INVXLHVT g1727(.A (n_39), .Y (n_44));
  INVXLHVT g1728(.A (n_38), .Y (n_43));
  INVXLHVT g1729(.A (n_37), .Y (n_42));
  INVXLHVT g1730(.A (n_36), .Y (n_41));
  INVXLHVT g1731(.A (n_35), .Y (n_40));
  AOI222XL g1732__1617(.A0 (data_save[2]), .A1 (n_27), .B0
       (data_save[1]), .B1 (n_20), .C0 (ext_data_in[2]), .C1 (n_7), .Y
       (n_39));
  AOI222XL g1733__2802(.A0 (data_save[1]), .A1 (n_27), .B0
       (data_save[0]), .B1 (n_20), .C0 (ext_data_in[1]), .C1 (n_7), .Y
       (n_38));
  AOI222XL g1734__1705(.A0 (data_save[7]), .A1 (n_27), .B0
       (data_save[6]), .B1 (n_20), .C0 (ext_data_in[7]), .C1 (n_7), .Y
       (n_37));
  AOI222XL g1735__5122(.A0 (data_save[4]), .A1 (n_27), .B0
       (data_save[3]), .B1 (n_20), .C0 (ext_data_in[4]), .C1 (n_7), .Y
       (n_36));
  AOI222XL g1736__8246(.A0 (data_save[5]), .A1 (n_27), .B0
       (data_save[4]), .B1 (n_20), .C0 (ext_data_in[5]), .C1 (n_7), .Y
       (n_35));
  AOI21XL g1737__7098(.A0 (count_8[2]), .A1 (n_16), .B0 (n_28), .Y
       (n_34));
  AOI22XL g1738__6131(.A0 (data_save[6]), .A1 (n_27), .B0
       (ext_data_in[6]), .B1 (n_7), .Y (n_33));
  AO22XLHVT g1739__1881(.A0 (data_save[0]), .A1 (n_27), .B0
       (ext_data_in[0]), .B1 (n_7), .Y (n_32));
  AOI22XL g1740__5115(.A0 (data_save[3]), .A1 (n_27), .B0
       (ext_data_in[3]), .B1 (n_7), .Y (n_31));
  DFFQXLHVT \count_16_reg[3] (.CK (clk), .D (n_30), .Q (count_16[3]));
  DFFQXLHVT \count_8_reg[1] (.CK (clk), .D (n_29), .Q (count_8[1]));
  OAI2BB1XLHVT g1743__7482(.A0N (count_16[3]), .A1N (n_18), .B0 (n_22),
       .Y (n_30));
  NOR2XLHVT g1744__4733(.A (n_65), .B (n_21), .Y (n_29));
  NOR2XLHVT g1745__6161(.A (count_8[2]), .B (n_16), .Y (n_28));
  DFFQXLHVT \count_16_reg[1] (.CK (clk), .D (n_26), .Q (count_16[1]));
  DFFQXLHVT \count_16_reg[2] (.CK (clk), .D (n_25), .Q (count_16[2]));
  OAI31XL g1748__9315(.A0 (count_16[1]), .A1 (n_1), .A2 (n_8), .B0
       (n_17), .Y (n_26));
  OAI32XLHVT g1749__9945(.A0 (count_16[2]), .A1 (n_62), .A2 (n_8), .B0
       (n_2), .B1 (n_15), .Y (n_25));
  AOI21XL g1750__2883(.A0 (n_14), .A1 (n_3), .B0 (n_65), .Y (n_27));
  DFFQXLHVT count_8_indication_reg(.CK (clk), .D (n_19), .Q
       (count_8_indication));
  DFFQXLHVT \count_8_reg[0] (.CK (clk), .D (n_23), .Q (count_8[0]));
  DFFQXLHVT \count_16_reg[0] (.CK (clk), .D (n_24), .Q (count_16[0]));
  OAI22XL g1754__2346(.A0 (n_1), .A1 (n_9), .B0 (count_16[0]), .B1
       (n_8), .Y (n_24));
  OAI22XL g1755__1666(.A0 (count_8[0]), .A1 (n_0), .B0 (n_65), .B1
       (n_12), .Y (n_23));
  OR4XLHVT g1756__7410(.A (count_16[3]), .B (n_2), .C (n_62), .D (n_8),
       .Y (n_22));
  XNOR2XLHVT g1757__6417(.A (count_8[1]), .B (n_13), .Y (n_21));
  NOR2XLHVT g1758__5477(.A (n_14), .B (n_0), .Y (n_19));
  OAI21XL g1759__2398(.A0 (count_16[2]), .A1 (n_63), .B0 (n_15), .Y
       (n_18));
  OAI21XL g1760__5107(.A0 (n_10), .A1 (n_11), .B0 (count_16[1]), .Y
       (n_17));
  NOR2BXLHVT g1761__6260(.AN (n_14), .B (n_0), .Y (n_20));
  NAND2XL g1762__4319(.A (count_8[1]), .B (n_13), .Y (n_16));
  AOI21XL g1763__8428(.A0 (n_62), .A1 (n_4), .B0 (n_10), .Y (n_15));
  DFFQXLHVT \current_state_reg[0] (.CK (clk), .D (n_5), .Q
       (current_state[0]));
  DFFQXLHVT \current_state_reg[1] (.CK (clk), .D (n_6), .Q
       (current_state[1]));
  NAND3XL g1766__5526(.A (count_8[2]), .B (count_8[0]), .C
       (count_8[1]), .Y (n_14));
  NAND2XL g1767__6783(.A (count_8[0]), .B (n_64), .Y (n_12));
  NOR2XLHVT g1768__3680(.A (count_16[0]), .B (n_63), .Y (n_11));
  AND2XLHVT g1769__1617(.A (count_8[0]), .B (n_3), .Y (n_13));
  INVXLHVT g1771(.A (n_10), .Y (n_9));
  NOR2BXLHVT g1772__2802(.AN (next_state[1]), .B (rst), .Y (n_6));
  NOR2BXLHVT g1773__1705(.AN (next_state[0]), .B (rst), .Y (n_5));
  NOR2XLHVT g1774__5122(.A (rst), .B (baud_tick), .Y (n_10));
  NAND2XL g1775__8246(.A (baud_tick), .B (n_4), .Y (n_8));
  NOR2BXLHVT g1776__7098(.AN (n_61), .B (rst), .Y (n_7));
  INVXLHVT g1778(.A (n_63), .Y (n_4));
  INVXLHVT g1779(.A (n_64), .Y (n_3));
  INVXLHVT g1782(.A (count_16[2]), .Y (n_2));
  INVXLHVT g1787(.A (count_16[0]), .Y (n_1));
  NAND2BXLHVT g2__6131(.AN (n_65), .B (n_3), .Y (n_0));
endmodule

module uart_top_design(clk, rst, address, write_data, we, tx, rx, re,
     read_data);
  input clk, rst, we, rx, re;
  input [1:0] address;
  input [31:0] write_data;
  output tx;
  output [7:0] read_data;
  wire clk, rst, we, rx, re;
  wire [1:0] address;
  wire [31:0] write_data;
  wire tx;
  wire [7:0] read_data;
  wire [31:0] baud_division;
  wire [7:0] data_in;
  wire [7:0] data_out;
  wire UNCONNECTED4, UNCONNECTED5, UNCONNECTED6, UNCONNECTED7,
       UNCONNECTED8, UNCONNECTED9, UNCONNECTED10, UNCONNECTED11;
  wire UNCONNECTED12, UNCONNECTED13, UNCONNECTED14, UNCONNECTED15,
       UNCONNECTED16, UNCONNECTED17, UNCONNECTED18, UNCONNECTED19;
  wire UNCONNECTED20, UNCONNECTED21, UNCONNECTED22, UNCONNECTED23,
       UNCONNECTED24, UNCONNECTED25, UNCONNECTED26, UNCONNECTED27;
  wire UNCONNECTED28, UNCONNECTED29, UNCONNECTED30, UNCONNECTED31,
       UNCONNECTED32, UNCONNECTED33, UNCONNECTED34, UNCONNECTED35;
  wire UNCONNECTED36, UNCONNECTED37, UNCONNECTED38, UNCONNECTED39,
       UNCONNECTED40, UNCONNECTED41, UNCONNECTED42, UNCONNECTED43;
  wire UNCONNECTED44, UNCONNECTED45, UNCONNECTED46, UNCONNECTED47,
       UNCONNECTED48, UNCONNECTED49, UNCONNECTED50, UNCONNECTED51;
  wire UNCONNECTED52, baud_tick, enable, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_37;
  wire n_38, n_39, n_40, n_41;
  uart_baud_rate uut_baud_rate(.clk (clk), .rst (rst), .baud_division
       (baud_division), .en (enable), .baud_tick (baud_tick));
  uart_rx uut_rx(.clk (clk), .rst (rst), .baud_tick (baud_tick), .rx
       (rx), .ext_data_out (data_in));
  uart_tx uut_tx(.clk (clk), .rst (rst), .baud_tick (baud_tick),
       .ext_data_in (data_out), .en (enable), .tx (tx));
  TLATNX2 \read_data_reg[7] (.GN (n_41), .D (data_in[7]), .Q
       (read_data[7]), .QN (UNCONNECTED4));
  TLATNX2 \read_data_reg[6] (.GN (n_41), .D (data_in[6]), .Q
       (read_data[6]), .QN (UNCONNECTED5));
  TLATNX2 \read_data_reg[4] (.GN (n_41), .D (data_in[4]), .Q
       (read_data[4]), .QN (UNCONNECTED6));
  TLATNX2 \read_data_reg[0] (.GN (n_41), .D (data_in[0]), .Q
       (read_data[0]), .QN (UNCONNECTED7));
  TLATXLHVT \baud_division_reg[24] (.G (n_40), .D (n_25), .Q
       (baud_division[24]), .QN (UNCONNECTED8));
  TLATXLHVT \baud_division_reg[8] (.G (n_40), .D (n_14), .Q
       (baud_division[8]), .QN (UNCONNECTED9));
  TLATXLHVT \baud_division_reg[7] (.G (n_40), .D (n_19), .Q
       (baud_division[7]), .QN (UNCONNECTED10));
  TLATXLHVT \baud_division_reg[23] (.G (n_40), .D (n_5), .Q
       (baud_division[23]), .QN (UNCONNECTED11));
  TLATXLHVT \baud_division_reg[6] (.G (n_40), .D (n_18), .Q
       (baud_division[6]), .QN (UNCONNECTED12));
  TLATXLHVT \baud_division_reg[5] (.G (n_40), .D (n_16), .Q
       (baud_division[5]), .QN (UNCONNECTED13));
  TLATXLHVT \baud_division_reg[31] (.G (n_40), .D (n_31), .Q
       (baud_division[31]), .QN (UNCONNECTED14));
  TLATXLHVT \baud_division_reg[22] (.G (n_40), .D (n_26), .Q
       (baud_division[22]), .QN (UNCONNECTED15));
  TLATXLHVT \baud_division_reg[4] (.G (n_40), .D (n_37), .Q
       (baud_division[4]), .QN (UNCONNECTED16));
  TLATXLHVT \baud_division_reg[3] (.G (n_40), .D (n_17), .Q
       (baud_division[3]), .QN (UNCONNECTED17));
  TLATXLHVT \baud_division_reg[21] (.G (n_40), .D (n_6), .Q
       (baud_division[21]), .QN (UNCONNECTED18));
  TLATXLHVT \baud_division_reg[2] (.G (n_40), .D (n_20), .Q
       (baud_division[2]), .QN (UNCONNECTED19));
  TLATXLHVT \baud_division_reg[1] (.G (n_40), .D (n_15), .Q
       (baud_division[1]), .QN (UNCONNECTED20));
  TLATNX2 \read_data_reg[3] (.GN (n_41), .D (data_in[3]), .Q
       (read_data[3]), .QN (UNCONNECTED21));
  TLATXLHVT \baud_division_reg[30] (.G (n_40), .D (n_32), .Q
       (baud_division[30]), .QN (UNCONNECTED22));
  TLATXLHVT \baud_division_reg[20] (.G (n_40), .D (n_24), .Q
       (baud_division[20]), .QN (UNCONNECTED23));
  TLATXLHVT \baud_division_reg[0] (.G (n_40), .D (n_34), .Q
       (baud_division[0]), .QN (UNCONNECTED24));
  TLATNXLHVT \data_out_reg[7] (.GN (n_39), .D (n_19), .Q (data_out[7]),
       .QN (UNCONNECTED25));
  TLATXLHVT \baud_division_reg[19] (.G (n_40), .D (n_13), .Q
       (baud_division[19]), .QN (UNCONNECTED26));
  TLATNXLHVT \data_out_reg[6] (.GN (n_39), .D (n_18), .Q (data_out[6]),
       .QN (UNCONNECTED27));
  TLATNXLHVT \data_out_reg[0] (.GN (n_39), .D (n_34), .Q (data_out[0]),
       .QN (UNCONNECTED28));
  TLATXLHVT \baud_division_reg[29] (.G (n_40), .D (n_33), .Q
       (baud_division[29]), .QN (UNCONNECTED29));
  TLATXLHVT \baud_division_reg[18] (.G (n_40), .D (n_27), .Q
       (baud_division[18]), .QN (UNCONNECTED30));
  TLATNXLHVT \data_out_reg[4] (.GN (n_39), .D (n_37), .Q (data_out[4]),
       .QN (UNCONNECTED31));
  TLATNXLHVT \data_out_reg[3] (.GN (n_39), .D (n_17), .Q (data_out[3]),
       .QN (UNCONNECTED32));
  TLATXLHVT \baud_division_reg[17] (.G (n_40), .D (n_12), .Q
       (baud_division[17]), .QN (UNCONNECTED33));
  TLATNXLHVT \data_out_reg[2] (.GN (n_39), .D (n_20), .Q (data_out[2]),
       .QN (UNCONNECTED34));
  TLATNXLHVT \data_out_reg[1] (.GN (n_39), .D (n_15), .Q (data_out[1]),
       .QN (UNCONNECTED35));
  TLATNX2 \read_data_reg[5] (.GN (n_41), .D (data_in[5]), .Q
       (read_data[5]), .QN (UNCONNECTED36));
  TLATNX2 \read_data_reg[2] (.GN (n_41), .D (data_in[2]), .Q
       (read_data[2]), .QN (UNCONNECTED37));
  TLATXLHVT \baud_division_reg[28] (.G (n_40), .D (n_29), .Q
       (baud_division[28]), .QN (UNCONNECTED38));
  TLATXLHVT \baud_division_reg[16] (.G (n_40), .D (n_23), .Q
       (baud_division[16]), .QN (UNCONNECTED39));
  TLATNXLHVT \data_out_reg[5] (.GN (n_39), .D (n_16), .Q (data_out[5]),
       .QN (UNCONNECTED40));
  TLATNXLHVT enable_reg(.GN (n_38), .D (n_34), .Q (enable), .QN
       (UNCONNECTED41));
  TLATXLHVT \baud_division_reg[15] (.G (n_40), .D (n_7), .Q
       (baud_division[15]), .QN (UNCONNECTED42));
  TLATXLHVT \baud_division_reg[27] (.G (n_40), .D (n_9), .Q
       (baud_division[27]), .QN (UNCONNECTED43));
  TLATXLHVT \baud_division_reg[14] (.G (n_40), .D (n_21), .Q
       (baud_division[14]), .QN (UNCONNECTED44));
  TLATXLHVT \baud_division_reg[13] (.G (n_40), .D (n_8), .Q
       (baud_division[13]), .QN (UNCONNECTED45));
  TLATNX2 \read_data_reg[1] (.GN (n_41), .D (data_in[1]), .Q
       (read_data[1]), .QN (UNCONNECTED46));
  TLATXLHVT \baud_division_reg[26] (.G (n_40), .D (n_30), .Q
       (baud_division[26]), .QN (UNCONNECTED47));
  TLATXLHVT \baud_division_reg[12] (.G (n_40), .D (n_22), .Q
       (baud_division[12]), .QN (UNCONNECTED48));
  TLATXLHVT \baud_division_reg[11] (.G (n_40), .D (n_10), .Q
       (baud_division[11]), .QN (UNCONNECTED49));
  TLATXLHVT \baud_division_reg[25] (.G (n_40), .D (n_4), .Q
       (baud_division[25]), .QN (UNCONNECTED50));
  TLATXLHVT \baud_division_reg[10] (.G (n_40), .D (n_28), .Q
       (baud_division[10]), .QN (UNCONNECTED51));
  TLATXLHVT \baud_division_reg[9] (.G (n_40), .D (n_11), .Q
       (baud_division[9]), .QN (UNCONNECTED52));
  AOI21XL g589__1881(.A0 (address[0]), .A1 (n_36), .B0 (rst), .Y
       (n_38));
  OAI21XL g590__5115(.A0 (address[0]), .A1 (n_35), .B0 (n_1), .Y
       (n_40));
  NAND4XL g591__7482(.A (n_2), .B (re), .C (address[0]), .D
       (address[1]), .Y (n_41));
  AOI31XL g592__4733(.A0 (we), .A1 (address[1]), .A2 (n_3), .B0 (rst),
       .Y (n_39));
  INVXLHVT g593(.A (n_35), .Y (n_36));
  AND2XLHVT g594__6161(.A (n_2), .B (write_data[29]), .Y (n_33));
  AND2XLHVT g595__9315(.A (n_1), .B (write_data[30]), .Y (n_32));
  AND2XLHVT g596__9945(.A (n_2), .B (write_data[31]), .Y (n_31));
  AND2XLHVT g597__2883(.A (n_1), .B (write_data[26]), .Y (n_30));
  AND2XLHVT g598__2346(.A (n_2), .B (write_data[28]), .Y (n_29));
  AND2XLHVT g599__1666(.A (n_1), .B (write_data[10]), .Y (n_28));
  AND2XLHVT g600__7410(.A (n_2), .B (write_data[18]), .Y (n_27));
  AND2XLHVT g601__6417(.A (n_1), .B (write_data[22]), .Y (n_26));
  AND2XLHVT g602__5477(.A (n_2), .B (write_data[24]), .Y (n_25));
  AND2XLHVT g603__2398(.A (n_1), .B (write_data[20]), .Y (n_24));
  AND2XLHVT g604__5107(.A (n_2), .B (write_data[16]), .Y (n_23));
  AND2XLHVT g605__6260(.A (n_1), .B (write_data[12]), .Y (n_22));
  AND2XLHVT g606__4319(.A (n_2), .B (write_data[14]), .Y (n_21));
  AND2XLHVT g607__8428(.A (n_1), .B (write_data[4]), .Y (n_37));
  NAND2BXLHVT g608__5526(.AN (address[1]), .B (we), .Y (n_35));
  AND2XLHVT g609__6783(.A (n_2), .B (write_data[0]), .Y (n_34));
  AND2XLHVT g610__3680(.A (n_1), .B (write_data[8]), .Y (n_14));
  AND2XLHVT g611__1617(.A (n_2), .B (write_data[19]), .Y (n_13));
  AND2XLHVT g612__2802(.A (n_1), .B (write_data[17]), .Y (n_12));
  AND2XLHVT g613__1705(.A (n_2), .B (write_data[9]), .Y (n_11));
  AND2XLHVT g614__5122(.A (n_1), .B (write_data[11]), .Y (n_10));
  AND2XLHVT g615__8246(.A (n_2), .B (write_data[27]), .Y (n_9));
  AND2XLHVT g616__7098(.A (n_1), .B (write_data[13]), .Y (n_8));
  AND2XLHVT g617__6131(.A (n_2), .B (write_data[15]), .Y (n_7));
  AND2XLHVT g618__1881(.A (n_1), .B (write_data[21]), .Y (n_6));
  AND2XLHVT g619__5115(.A (n_2), .B (write_data[23]), .Y (n_5));
  AND2XLHVT g620__7482(.A (n_1), .B (write_data[25]), .Y (n_4));
  AND2XLHVT g621__4733(.A (n_2), .B (write_data[2]), .Y (n_20));
  AND2XLHVT g622__6161(.A (n_1), .B (write_data[7]), .Y (n_19));
  AND2XLHVT g623__9315(.A (n_2), .B (write_data[6]), .Y (n_18));
  AND2XLHVT g624__9945(.A (n_1), .B (write_data[3]), .Y (n_17));
  AND2XLHVT g625__2883(.A (n_2), .B (write_data[5]), .Y (n_16));
  AND2XLHVT g626__2346(.A (n_1), .B (write_data[1]), .Y (n_15));
  INVXLHVT g627(.A (address[0]), .Y (n_3));
  CLKINVX1 g628(.A (rst), .Y (n_2));
  INVXLHVT drc_bufs634(.A (rst), .Y (n_1));
endmodule

